name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: SSH into GCP and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_URL }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.USER_NAME }}/repository/4th-SC-Team-8-BE
            git pull origin main
            ./gradlew build -x test
            docker build -t my-app-image:latest -f Dockerfile .
            docker stop my-app-container || true
            docker rm my-app-container || true
            docker run -d --name my-app-container -p 8080:8080 my-app-image:latest
